services:
  client:
    build: ./client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3002:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - SEED_DASHBOARD_CONFIG=true
      - MONGO_URI=mongodb://root:root@mongo:27017/dashboard?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
